### ISSUE TITLE
Quality of rendered text is very bad

### ISSUE THREAD

**Issue by olivia-fl** [tomaka/glium_text#2]
When I run the hello_world example the rendered text looks really bad (at least on my computer). Here is a screenshot:

![Screenshot](https://cloud.githubusercontent.com/assets/6504174/6013894/f526fcaa-ab0f-11e4-8f59-5cb3def49cd1.png)

I have very little familiarity with freetype so I don't really know how to fix this.

**Comment by tomaka** [comment]
It's the same for me.
I wrote this crate to get quick text rendering on the screen. Its code was copy-pasted from a C++ library that I wrote a few years ago that was also meant for quick-and-dirty text rendering.

There are many issues with this library, however to fix them I'd need to dive in freetype again, which I haven't done in years.
